In [45]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KDTree

In [80]:
XEXAMPLE = np.array([[1,1],[2,2], [3,3]])  # 3 points in 2 dimensions
treeEXAMPLE = KDTree(XEXAMPLE, metric='l1')                                         # !!!
distEXAMPLE, indEXAMPLE = treeEXAMPLE.query([[1.25, 1.35]], k=2)
print(indEXAMPLE)  # indices of 2 closest neighbors
print(distEXAMPLE)  # distances to 2 closest neighbors

[[0 1]]
[[0.6 1.4]]

In [8]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("C:/Users/btspanswick/Desktop/PYproject/data/cars.csv",
                  header=None, names=headers, na_values="?" )
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [9]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [14]:
obj_df = df.select_dtypes(include=['object']).copy()
other_df = df.select_dtypes(include=['float64','int64']).copy()
obj_df.head()
other_df.head()

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [37]:
dummy_df = pd.get_dummies(obj_df)

In [39]:
cars_dummy = other_df.join(dummy_df)
cars_dummy.head()

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,...,num_cylinders_twelve,num_cylinders_two,fuel_system_1bbl,fuel_system_2bbl,fuel_system_4bbl,fuel_system_idi,fuel_system_mfi,fuel_system_mpfi,fuel_system_spdi,fuel_system_spfi
0,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
1,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
2,1,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,0,0,0,0,0,0,0,1,0,0
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0

In [40]:
cars_dummy

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,...,num_cylinders_twelve,num_cylinders_two,fuel_system_1bbl,fuel_system_2bbl,fuel_system_4bbl,fuel_system_idi,fuel_system_mfi,fuel_system_mpfi,fuel_system_spdi,fuel_system_spfi
0,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
1,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
2,1,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,0,0,0,0,0,0,0,1,0,0
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
5,2,NaN,99.8,177.3,66.3,53.1,2507,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
6,1,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
7,1,NaN,105.8,192.7,71.4,55.7,2954,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
8,1,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.40,...,0,0,0,0,0,0,0,1,0,0
9,0,NaN,99.5,178.2,67.9,52.0,3053,131,3.13,3.40,...,0,0,0,0,0,0,0,1,0,0
10,2,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.80,...,0,0,0,0,0,0,0,1,0,0
11,0,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.80,...,0,0,0,0,0,0,0,1,0,0
12,0,188.0,101.2,176.8,64.8,54.3,2710,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
13,0,188.0,101.2,176.8,64.8,54.3,2765,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
14,1,NaN,103.5,189.0,66.9,55.7,3055,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
15,0,NaN,103.5,189.0,66.9,55.7,3230,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
16,0,NaN,103.5,193.8,67.9,53.7,3380,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
17,0,NaN,110.0,197.0,70.9,56.3,3505,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
18,2,121.0,88.4,141.1,60.3,53.2,1488,61,2.91,3.03,...,0,0,0,1,0,0,0,0,0,0
19,1,98.0,94.5,155.9,63.6,52.0,1874,90,3.03,3.11,...,0,0,0,1,0,0,0,0,0,0
20,0,81.0,94.5,158.8,63.6,52.0,1909,90,3.03,3.11,...,0,0,0,1,0,0,0,0,0,0
21,1,118.0,93.7,157.3,63.8,50.8,1876,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
22,1,118.0,93.7,157.3,63.8,50.8,1876,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
23,1,118.0,93.7,157.3,63.8,50.8,2128,98,3.03,3.39,...,0,0,0,0,0,0,0,1,0,0
24,1,148.0,93.7,157.3,63.8,50.6,1967,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
25,1,148.0,93.7,157.3,63.8,50.6,1989,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
26,1,148.0,93.7,157.3,63.8,50.6,1989,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
27,1,148.0,93.7,157.3,63.8,50.6,2191,98,3.03,3.39,...,0,0,0,0,0,0,0,1,0,0
28,-1,110.0,103.3,174.6,64.6,59.8,2535,122,3.34,3.46,...,0,0,0,1,0,0,0,0,0,0
29,3,145.0,95.9,173.2,66.3,50.2,2811,156,3.60,3.90,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,-1,65.0,102.4,175.6,66.5,53.9,2414,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
176,-1,65.0,102.4,175.6,66.5,54.9,2414,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
177,-1,65.0,102.4,175.6,66.5,53.9,2458,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
178,3,197.0,102.9,183.5,67.7,52.0,2976,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
179,3,197.0,102.9,183.5,67.7,52.0,3016,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
180,-1,90.0,104.5,187.8,66.5,54.1,3131,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
181,-1,NaN,104.5,187.8,66.5,54.1,3151,161,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
182,2,122.0,97.3,171.7,65.5,55.7,2261,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
183,2,122.0,97.3,171.7,65.5,55.7,2209,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
184,2,94.0,97.3,171.7,65.5,55.7,2264,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
185,2,94.0,97.3,171.7,65.5,55.7,2212,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
186,2,94.0,97.3,171.7,65.5,55.7,2275,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
187,2,94.0,97.3,171.7,65.5,55.7,2319,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
188,2,94.0,97.3,171.7,65.5,55.7,2300,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
189,3,NaN,94.5,159.3,64.2,55.6,2254,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
190,3,256.0,94.5,165.7,64.0,51.4,2221,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
191,0,NaN,100.4,180.2,66.9,55.1,2661,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
192,0,NaN,100.4,180.2,66.9,55.1,2579,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
193,0,NaN,100.4,183.1,66.9,55.1,2563,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
194,-2,103.0,104.3,188.8,67.2,56.2,2912,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
195,-1,74.0,104.3,188.8,67.2,57.5,3034,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
196,-2,103.0,104.3,188.8,67.2,56.2,2935,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
197,-1,74.0,104.3,188.8,67.2,57.5,3042,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
198,-2,103.0,104.3,188.8,67.2,56.2,3045,130,3.62,3.15,...,0,0,0,0,0,0,0,1,0,0
199,-1,74.0,104.3,188.8,67.2,57.5,3157,130,3.62,3.15,...,0,0,0,0,0,0,0,1,0,0
200,-1,95.0,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
201,-1,95.0,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
202,-1,95.0,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,...,0,0,0,0,0,0,0,1,0,0
203,-1,95.0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
204,-1,95.0,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0

In [41]:
test_car = cars_dummy.iloc[4]

test_car

symboling                    2.00
normalized_losses          164.00
wheel_base                  99.40
length                     176.60
width                       66.40
height                      54.30
curb_weight               2824.00
engine_size                136.00
bore                         3.19
stroke                       3.40
compression_ratio            8.00
horsepower                 115.00
peak_rpm                  5500.00
city_mpg                    18.00
highway_mpg                 22.00
price                    17450.00
make_alfa-romero             0.00
make_audi                    1.00
make_bmw                     0.00
make_chevrolet               0.00
make_dodge                   0.00
make_honda                   0.00
make_isuzu                   0.00
make_jaguar                  0.00
make_mazda                   0.00
make_mercedes-benz           0.00
make_mercury                 0.00
make_mitsubishi              0.00
make_nissan                  0.00
make_peugot                  0.00
                           ...
body_style_hatchback         0.00
body_style_sedan             1.00
body_style_wagon             0.00
drive_wheels_4wd             1.00
drive_wheels_fwd             0.00
drive_wheels_rwd             0.00
engine_location_front        1.00
engine_location_rear         0.00
engine_type_dohc             0.00
engine_type_dohcv            0.00
engine_type_l                0.00
engine_type_ohc              1.00
engine_type_ohcf             0.00
engine_type_ohcv             0.00
engine_type_rotor            0.00
num_cylinders_eight          0.00
num_cylinders_five           1.00
num_cylinders_four           0.00
num_cylinders_six            0.00
num_cylinders_three          0.00
num_cylinders_twelve         0.00
num_cylinders_two            0.00
fuel_system_1bbl             0.00
fuel_system_2bbl             0.00
fuel_system_4bbl             0.00
fuel_system_idi              0.00
fuel_system_mfi              0.00
fuel_system_mpfi             1.00
fuel_system_spdi             0.00
fuel_system_spfi             0.00
Name: 4, Length: 76, dtype: float64

In [57]:
dummy = cars_dummy.values
car = test_car.values
car = car.reshape(1, -1)

dummy
car

array([[2.000e+00, 1.640e+02, 9.940e+01, 1.766e+02, 6.640e+01, 5.430e+01,
        2.824e+03, 1.360e+02, 3.190e+00, 3.400e+00, 8.000e+00, 1.150e+02,
        5.500e+03, 1.800e+01, 2.200e+01, 1.745e+04, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

In [70]:
KDTree.valid_metrics

['euclidean',
 'l2',
 'minkowski',
 'p',
 'manhattan',
 'cityblock',
 'l1',
 'chebyshev',
 'infinity']

In [66]:
treel1 = KDTree(dummy, metric='l1')                                
distl1, indl1 = treel1.query(car, k=5)
print(indl1)  # indices of 2 closest neighbors
print(distl1)  # distances to 2 closest neighbors

[[  4   6 136 200 104]]
[[  0.   327.4  823.88 955.94 956.47]]

In [ ]:
print(df.loc[[4, 6, 136, 200, 104]])

In [71]:
treeE = KDTree(dummy, metric='euclidean')                                
distE, indE = treeE.query(car, k=5)
print(indE)  # indices of 2 closest neighbors
print(distE)  # distances to 2 closest neighbors

[[  4   6 104 200 136]]
[[  0.         261.53657488 468.08963298 630.49605915 702.02462307]]

In [83]:
print(df.loc[[4,6,104,200,136]])

     symboling  normalized_losses    make fuel_type aspiration num_doors  \
4            2              164.0    audi       gas        std      four
6            1              158.0    audi       gas        std      four
104          3              194.0  nissan       gas        std       two
200         -1               95.0   volvo       gas        std      four
136          3              150.0    saab       gas      turbo       two

    body_style drive_wheels engine_location  wheel_base   ...     engine_size  \
4        sedan          4wd           front        99.4   ...             136
6        sedan          fwd           front       105.8   ...             136
104  hatchback          rwd           front        91.3   ...             181
200      sedan          rwd           front       109.1   ...             141
136  hatchback          fwd           front        99.1   ...             121

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
4           mpfi  3.19    3.40               8.0      115.0    5500.0
6           mpfi  3.19    3.40               8.5      110.0    5500.0
104         mpfi  3.43    3.27               9.0      160.0    5200.0
200         mpfi  3.78    3.15               9.5      114.0    5400.0
136         mpfi  3.54    3.07               9.0      160.0    5500.0

    city_mpg  highway_mpg    price
4         18           22  17450.0
6         19           25  17710.0
104       19           25  17199.0
200       23           28  16845.0
136       19           26  18150.0

[5 rows x 26 columns]

In [78]:
treeMan = KDTree(dummy, metric='l1')                                
distMan, indMan = treeMan.query(car, k=5)
print(indMan)  # indices of 2 closest neighbors
print(distMan)  # distances to 2 closest neighbors

[[  4   6 136 200 104]]
[[  0.   327.4  823.88 955.94 956.47]]

In [79]:
print(df.loc[[4,6,136,200,104]])

     symboling  normalized_losses    make fuel_type aspiration num_doors  \
4            2              164.0    audi       gas        std      four
6            1              158.0    audi       gas        std      four
136          3              150.0    saab       gas      turbo       two
200         -1               95.0   volvo       gas        std      four
104          3              194.0  nissan       gas        std       two

    body_style drive_wheels engine_location  wheel_base   ...     engine_size  \
4        sedan          4wd           front        99.4   ...             136
6        sedan          fwd           front       105.8   ...             136
136  hatchback          fwd           front        99.1   ...             121
200      sedan          rwd           front       109.1   ...             141
104  hatchback          rwd           front        91.3   ...             181

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
4           mpfi  3.19    3.40               8.0      115.0    5500.0
6           mpfi  3.19    3.40               8.5      110.0    5500.0
136         mpfi  3.54    3.07               9.0      160.0    5500.0
200         mpfi  3.78    3.15               9.5      114.0    5400.0
104         mpfi  3.43    3.27               9.0      160.0    5200.0

    city_mpg  highway_mpg    price
4         18           22  17450.0
6         19           25  17710.0
136       19           26  18150.0
200       23           28  16845.0
104       19           25  17199.0

[5 rows x 26 columns]