In [230]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KDTree

# Using data from: https://www.kaggle.com/speckledpingu/nfl-qb-stats/home

In [231]:
df = pd.read_csv("C:/Users/btspanswick/Desktop/PYproject/data/QBStats.csv")
df['freq'] = df.groupby('qb')['qb'].transform('count')
df.head()

,qb,att,cmp,yds,ypa,td,int,lg,sack,loss,rate,game_points,home_away,year,freq
0,Boomer EsiasonBEsiason,38,25,237.0,6.2,0,0,20,2.0,11.0,82.9,13,away,1996,17
1,Jim HarbaughJHarbaugh,25,16,196.0,7.8,2,1,35t,0.0,0.0,98.1,20,home,1996,61
2,Paul JustinPJustin,8,5,53.0,6.6,0,0,30,1.0,11.0,81.8,20,home,1996,24
3,Jeff GeorgeJGeorge,35,16,215.0,6.1,0,0,55,7.0,53.0,65.8,6,away,1996,47
4,Kerry CollinsKCollins,31,17,198.0,6.4,2,0,30,4.0,12.0,95.9,29,home,1996,181

In [249]:
grouped_df = df.drop(columns=['year', 'home_away'])
grouped_df = grouped_df.groupby(['qb']).mean()
grouped_df

,att,cmp,yds,ypa,td,sack,loss,rate,game_points,freq
qb,,,,,,,,,,
A.J. FeeleyAFeeley,28.222222,15.740741,171.037037,6.014815,1.037037,1.629630,10.222222,71.125926,18.888889,27.0
A.J. McCarronAMcCarron,19.833333,13.166667,142.333333,6.466667,1.000000,2.000000,10.500000,93.516667,25.500000,6.0
Aaron BrooksABrooks,32.922222,18.588889,225.122222,6.894444,1.366667,2.611111,16.155556,79.385556,20.644444,90.0
Aaron CraverACraver,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,16.500000,2.0
Aaron RodgersARodgers,33.028369,21.517730,261.184397,7.941844,2.106383,2.418440,15.340426,103.175177,27.411348,141.0
Abdul-Karim Al-JabbarAAl-Jabbar,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,37.000000,1.0
Ace SandersASanders,1.000000,1.000000,21.000000,21.000000,1.000000,0.000000,0.000000,158.300000,27.000000,1.0
Adam JonesAJones,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,13.000000,0.000000,3.000000,1.0
Adam PodleshAPodlesh,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,31.000000,1.0
Adam VinatieriAVinatieri,1.000000,1.000000,4.000000,4.000000,1.000000,0.000000,0.000000,122.900000,40.000000,1.0
Adimchinobe EchemanduAEchemandu,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,0.000000,1.0
Adrian PetersonAPeterson,1.000000,1.000000,9.000000,9.000000,1.000000,0.000000,0.000000,143.800000,33.000000,1.0
Ahman GreenAGreen,1.000000,0.500000,10.000000,10.000000,0.500000,0.000000,0.000000,98.950000,32.000000,2.0
Akili SmithASmith,21.952381,10.238095,105.333333,4.819048,0.238095,2.809524,15.571429,56.057143,11.190476,21.0
Alex SmithASmith,29.134752,17.985816,197.489362,6.804965,1.113475,2.503546,14.156028,85.716312,21.638298,141.0
Alex TanneyATanney,14.000000,10.000000,99.000000,7.100000,1.000000,3.000000,34.000000,114.900000,24.000000,1.0
Alex Van PeltAVan Pelt,17.653846,9.692308,110.730769,5.469231,0.538462,0.730769,4.346154,59.469231,16.192308,26.0
Amani ToomerAToomer,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,7.000000,1.0
Andre ReedAReed,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,20.000000,0.000000,20.000000,1.0
Andrew LuckALuck,37.871429,22.428571,272.542857,7.285714,1.885714,2.228571,14.142857,88.325714,25.242857,70.0
Andrew PinnockAPinnock,2.000000,1.000000,0.500000,1.000000,1.000000,NaN,NaN,NaN,34.000000,1.0
Andrew WalterAWalter,22.200000,11.600000,127.933333,5.540000,0.200000,3.400000,19.666667,53.580000,9.800000,15.0
Andy DaltonADalton,32.903226,20.645161,238.860215,7.420430,1.526882,1.946237,11.580645,90.896774,23.752688,93.0
Andy LeeALee,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,16.000000,1.0
Anquan BoldinABoldin,1.000000,0.250000,-1.500000,-1.500000,0.000000,0.000000,0.000000,39.600000,18.750000,4.0
Anthony WrightAWright,22.407407,12.296296,132.962963,5.929630,0.740741,2.037037,14.592593,66.914815,18.740741,27.0
Antonio AndrewsAAndrews,1.000000,1.000000,41.000000,41.000000,1.000000,0.000000,0.000000,158.300000,8.000000,1.0
Antonio BrownABrown,0.833333,0.500000,5.833333,5.833333,0.166667,0.333333,2.500000,66.000000,23.500000,6.0
Antonio MorrisonAMorrison,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,24.000000,1.0
Antwaan Randle ElARandle El,1.038462,0.846154,12.423077,11.615385,0.230769,0.076923,0.807692,95.765385,19.923077,26.0
...,...,...,...,...,...,...,...,...,...,...
Travis BrownTBrown,13.000000,7.250000,90.250000,6.200000,0.250000,0.500000,2.250000,67.350000,9.250000,4.0
Travis HenryTHenry,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.0
Trent DilferTDilfer,25.235849,14.122642,163.311321,6.363208,1.018868,1.962264,12.801887,73.240566,18.867925,106.0
Trent EdwardsTEdwards,25.108108,15.216216,163.054054,6.367568,0.702703,1.864865,13.027027,75.554054,17.162162,37.0
Trent GreenTGreen,31.166667,18.883333,237.291667,7.681667,1.350000,2.158333,13.508333,85.817500,25.216667,120.0
Tress WayTWay,1.000000,1.000000,31.000000,31.000000,0.000000,0.000000,0.000000,118.800000,29.000000,1.0
Trevone BoykinTBoykin,6.000000,4.333333,48.333333,8.966667,0.333333,0.333333,1.666667,96.900000,34.000000,3.0
Trevor SiemianTSiemian,35.384615,20.846154,247.923077,7.323077,1.307692,2.230769,12.923077,90.184615,21.230769,13.0
Troy AikmanTAikman,29.880597,17.820896,199.029851,6.682090,1.000000,1.373134,9.970149,79.743284,20.507463,67.0
Troy BrownTBrown,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,20.000000,1.0
Troy SmithTSmith,14.625000,7.562500,108.375000,9.375000,0.500000,1.437500,8.875000,80.925000,24.125000,16.0
Ty DetmerTDetmer,27.000000,15.696970,183.696970,7.248485,1.000000,2.000000,11.575758,77.563636,19.787879,33.0
Tyler PalkoTPalko,17.500000,10.500000,103.875000,5.375000,0.250000,1.625000,11.625000,67.750000,6.875000,8.0
Tyler ThigpenTThigpen,22.130435,11.956522,140.086957,6.273913,0.913043,1.521739,9.608696,70.134783,15.956522,23.0
Tyrod TaylorTTaylor,24.314286,15.142857,178.771429,7.357143,1.057143,2.371429,12.485714,89.854286,24.914286,35.0
Tyrone WheatleyTWheatley,1.000000,1.000000,24.000000,24.000000,1.000000,0.000000,0.000000,158.300000,35.000000,1.0
Vince YoungVYoung,22.101695,12.796610,151.932203,7.332203,0.779661,1.406780,7.610169,74.284746,21.288136,59.0
Vinny TestaverdeVTestaverde,30.336207,17.827586,207.353448,6.891379,1.301724,1.491379,10.068966,81.191379,20.500000,116.0
Wade WilsonWWilson,11.545455,6.545455,69.272727,4.490909,0.636364,1.272727,10.000000,69.590909,16.545455,11.0
Wali LundyWLundy,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,9.000000,0.000000,13.000000,1.0
Wally RichardsonWRichardson,2.000000,1.000000,1.000000,0.500000,0.000000,0.000000,0.000000,56.200000,19.000000,1.0
Warren MoonWMoon,29.722222,16.888889,198.555556,6.991667,1.222222,2.111111,13.888889,76.963889,21.611111,36.0
Warrick DunnWDunn,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,31.000000,1.0
Wayne ChrebetWChrebet,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,21.000000,1.0
William FloydWFloyd,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,1.0
Willie DavisWDavis,1.000000,1.000000,22.000000,22.000000,1.000000,0.000000,0.000000,158.300000,9.000000,1.0
Willie ParkerWParker,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.600000,31.000000,1.0
Willie SneadWSnead,1.000000,1.000000,50.000000,50.000000,1.000000,0.000000,0.000000,158.300000,49.000000,1.0
Woodrow DantzlerWDantzler,0.500000,0.000000,0.000000,0.000000,0.000000,0.500000,2.500000,19.800000,13.000000,2.0
Zach MettenbergerZMettenberger,26.538462,16.000000,180.538462,6.676923,0.923077,2.384615,18.153846,70.615385,14.230769,13.0

In [233]:
grouped_df.dtypes

att            float64
cmp            float64
yds            float64
ypa            float64
td             float64
sack           float64
loss           float64
rate           float64
game_points    float64
freq           float64
dtype: object

In [234]:
bigben = grouped_df.loc['Ben RoethlisbergerBRoethlisberger']
bigben

att             32.064865
cmp             20.562162
yds            253.048649
ypa              8.075676
td               1.627027
sack             2.464865
loss            16.259459
rate            94.918919
game_points     23.821622
freq           185.000000
Name: Ben RoethlisbergerBRoethlisberger, dtype: float64

In [235]:
qbs = grouped_df.values
ben = bigben.values
ben = ben.reshape(1, -1)

ben

array([[ 32.06486486,  20.56216216, 253.04864865,   8.07567568,
          1.62702703,   2.46486486,  16.25945946,  94.91891892,
         23.82162162, 185.        ]])

In [236]:
qbs_sarray = grouped_df.to_records(index=True)

In [237]:
qbs_sarray
reference_df = pd.DataFrame(qbs_sarray)

In [238]:
KDTree.valid_metrics

['euclidean',
 'l2',
 'minkowski',
 'p',
 'manhattan',
 'cityblock',
 'l1',
 'chebyshev',
 'infinity']

In [245]:
treel1 = KDTree(qbs, metric='euclidean')                                
distl1, indl1 = treel1.query(ben, k=11)
print(indl1)  # indices of 2 closest neighbors
print(distl1)  # distances to 2 closest neighbors

[[ 40 506 105 234 211 448   4 221 440 370 292]]
[[ 0.          9.60682089 12.85403679 22.4510579  35.34404529 45.23555989
  45.67470045 46.02365261 48.72246624 49.20952117 50.83109879]]

In [246]:
results = indl1.tolist()
print(results)

[[40, 506, 105, 234, 211, 448, 4, 221, 440, 370, 292]]

In [247]:
most_similar = pd.DataFrame(reference_df.loc[results[0]])

print(most_similar)

                                    qb        att        cmp         yds  \
40   Ben RoethlisbergerBRoethlisberger  32.064865  20.562162  253.048649
506               Philip RiversPRivers  33.241573  21.410112  257.488764
105               Carson PalmerCPalmer  34.514286  21.582857  252.965714
234                Eli ManningEManning  34.105528  20.336683  240.623116
211              Donovan McNabbDMcNabb  32.569697  19.212121  225.915152
448                     Matt RyanMRyan  35.661972  23.154930  265.500000
4                Aaron RodgersARodgers  33.028369  21.517730  261.184397
221               Drew BledsoeDBledsoe  33.073333  19.346667  227.033333
440         Matt HasselbeckMHasselbeck  30.112994  18.203390  206.994350
370              Kerry CollinsKCollins  31.950276  17.928177  209.187845
292                  Jay CutlerJCutler  32.309353  20.014388  233.575540

          ypa        td      sack       loss        rate  game_points   freq
40   8.075676  1.627027  2.464865  16.259459   94.918919    23.821622  185.0
506  7.903371  1.764045  2.033708  12.235955   96.632584    25.275281  178.0
105  7.414857  1.628571  1.817143  12.651429   88.306857    23.057143  175.0
234  7.082412  1.597990  1.648241  11.452261   83.754774    23.623116  199.0
211  6.887879  1.418182  2.484848  15.915152   84.521818    22.715152  165.0
448  7.634507  1.690141  1.795775  11.838028   95.683803    25.154930  142.0
4    7.941844  2.106383  2.418440  15.340426  103.175177    27.411348  141.0
221  6.929333  1.320000  2.706667  18.180000   80.692000    21.306667  150.0
440  6.861017  1.197740  2.033898  12.768362   82.206780    21.853107  177.0
370  6.574033  1.071823  1.712707  11.359116   74.166851    19.690608  181.0
292  7.278417  1.496403  2.172662  13.532374   86.087770    22.381295  139.0